name: reproduced-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - anaconda-client=1.11.1
  - anaconda-navigator=2.4.0
  - anaconda-project=0.11.1
  - appdirs=1.4.4
  - arrow=1.2.3
  - astroid=2.14.2
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - attrs=22.1.0
  - autopep8=1.6.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - black=23.3.0
  - blas=1.0
  - bleach=4.1.0
  - boltons=23.0.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.6
  - comm=0.1.2
  - conda=23.3.1
  - conda-build=3.23.3
  - conda-content-trust=0.1.3
  - conda-pack=0.6.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - conda-repo-cli=1.0.41
  - conda-token=0.4.0
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - contourpy=1.2.0
  - cookiecutter=1.7.3
  - cryptography=39.0.1
  - cuda=11.8.0
  - cuda-cccl=12.1.55
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=12.1.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=12.1.55
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=12.1.55
  - cuda-demo-suite=12.1.55
  - cuda-documentation=12.1.55
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-memcheck=11.8.86
  - cuda-nsight-compute=12.1.0
  - cuda-nvcc=12.1.66
  - cuda-nvdisasm=12.1.55
  - cuda-nvml-dev=12.1.55
  - cuda-nvprof=12.1.55
  - cuda-nvprune=12.1.55
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-nvvp=12.1.55
  - cuda-profiler-api=12.1.55
  - cuda-runtime=11.8.0
  - cuda-sanitizer-api=12.1.55
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-visual-tools=11.8.0
  - cudatoolkit=11.3.1
  - cupy=12.0.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.6
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - entrypoints=0.4
  - executing=0.8.3
  - fastrlock=0.8
  - filelock=3.9.0
  - flake8=6.0.0
  - flit-core=3.8.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - future=0.18.3
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - inflection=0.5.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jaraco.classes=3.2.1
  - jedi=0.18.1
  - jellyfish=0.9.0
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jpeg=9e
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyterlab_pygments=0.1.2
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lazy-object-proxy=1.6.0
  - lerc=3.0
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.2.56
  - libcurand-dev=10.3.2.56
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.2
  - libiconv=1.16
  - liblief=0.12.3
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.5
  - libpng=1.6.39
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.5.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - llvmlite=0.39.1
  - lxml=4.9.2
  - lz4-c=1.9.4
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-patch=2.7.5
  - markupsafe=2.1.1
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - menuinst=1.4.19
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - more-itertools=8.12.0
  - mpmath=1.2.1
  - msys2-conda-epoch=20160418
  - mypy_extensions=0.4.3
  - navigator-updater=0.3.0
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - nsight-compute=2023.1.0.15
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.22.3
  - numpy-base=1.22.3
  - numpydoc=1.5.0
  - openssl=1.1.1w
  - packaging=23.0
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - paramiko=2.8.1
  - parso=0.8.3
  - pathlib=1.0.1
  - pathspec=0.10.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - pkginfo=1.9.6
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.4.0
  - powershell_shortcut=0.0.1
  - poyo=0.5.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - pycodestyle=2.10.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.0.1
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pylint=2.16.2
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyqtwebengine=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-libarchive-c=2.9
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.7.1
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytoolconfig=1.2.5
  - pytools=2022.1.14
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pywin32=305
  - pywin32-ctypes=0.2.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qdarkstyle=3.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - requests=2.28.1
  - rope=1.7.0
  - rtree=1.0.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.17.21
  - scipy=1.10.1
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.4.2
  - spyder-kernels=2.4.3
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2023c
  - ujson=5.4.0
  - unicodedata2=15.1.0
  - unidecode=1.2.0
  - urllib3=1.26.15
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - whatthepatch=1.0.2
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.14.1
  - xz=5.2.10
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - docopt==0.6.2
      - js2py==0.74
      - pipwin==0.5.2
      - pycuda==2022.1+cuda116
      - pyjsparser==2.7.1
      - pylint-venv==2.3.0
      - pyprind==2.11.3
      - pysmartdl==1.3.4
      - pytz-deprecation-shim==0.1.0.post0
      - qstylizer==0.2.2
      - qtawesome==1.2.2
      - torchaudio==2.0.0
      - torchvision==0.15.0
      - tzlocal==4.3
